[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.6"
actix-web = "4"
askama = "0.12.1"
askama_actix = "0.14.0"
serde = { version = "1.0.217", features = ["derive"] }

